---

- name: DevOps Bootcamp

  hosts: appserver

  gather_facts: no

  become: yes

  tasks:

    - name: Update APT package manager repositories cache

      become: true

      apt:

        update_cache: yes

    - name: Install OpenJDK Java

      become: yes

      apt:

        name: openjdk-8-jdk

        state: present

    - name: Install Maven using Ansible

      become: yes

      apt:

        name: maven

        state: present

    - name: Installs nginx web server

      become: yes

      apt:

       name: nginx

       state: present

      notify:

        - start nginx

    - name: Install docker dependencies

      apt:

        name: "{{item}}"

        state: present

        update_cache: yes

      loop:

        - apt-transport-https

        - ca-certificates

        - curl

        - gnupg-agent

        - software-properties-common

    - name: add GPG key

      apt_key:

        url: https://download.docker.com/linux/ubuntu/gpg

        state: present

    - name: add docker repository to apt

      apt_repository:

        repo: deb https://download.docker.com/linux/ubuntu bionic stable

        state: present

    - name: install docker

      apt:

        name: "{{item}}"

        state: latest

        update_cache: yes

      loop:

        - docker-ce

        - docker-ce-cli

        - containerd.io
    - name: deploy wartest application
      command: sudo docker run -it -d -p 8000:80 aishwaryadevops/webserver-image:v1
  handlers:

    - name: start nginx

      service: name=nginx state=started
